sudo: true
dist: trusty
language: python
python:
 - "3.5"
jobs:
 include:
   - script:
       - curl -LO --retry 3 https://raw.githubusercontent.com/precice/systemtests/develop/trigger_systemtests.py
       - travis_wait 60 python trigger_systemtests.py --adapter calculix --wait --st-branch EderK-ccx216
